Repository Turbo87/aprs-parser-rs, pull requests merged in 2022-01, with the labels that each got.

#9 Migrate from TravisCI to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: internal

#10 Improve CI config
  .github/workflows/ci.yml
Labels: internal

#11 `cargo fmt`
  .github/workflows/ci.yml
  examples/debug.rs
  src/callsign.rs
  src/error.rs
  src/lib.rs
  src/lonlat.rs
  src/message.rs
  src/position.rs
  src/timestamp.rs
Labels: internal

#12 `cargo clippy`
  .github/workflows/ci.yml
  src/callsign.rs
Labels: internal

#13 Replace `failure` with `thiserror`
  Cargo.toml
  src/error.rs
  src/lib.rs
Labels: internal

#14 Decrease MSRV to v1.38.0
  .github/workflows/ci.yml
Labels: internal

#15 Add `Cargo.lock` file
  .gitignore
  Cargo.lock
Labels: internal

#6 Use `Aprs` prefix for types
  src/callsign.rs
  src/error.rs
  src/lib.rs
  src/lonlat.rs
  src/message.rs
  src/position.rs
  src/timestamp.rs
Labels: breaking

#21 CI: Enable colored `cargo` output
  .github/workflows/ci.yml
Labels: internal

#20 lonlat: Extract `Latitude` and `Longitude` structs
  src/lib.rs
  src/lonlat.rs
  src/message.rs
  src/position.rs
Labels: enhancement, breaking
