Repository Turbo87/aprs-parser-rs, pull requests merged in 2022-08, with the labels that each got.

#5 Add support for APRS Messages
  src/error.rs
  src/lib.rs
  src/message.rs
  src/packet.rs
Labels: enhancement, breaking

#42 Raise minimum Rust version to v1.52.0
  .github/workflows/ci.yml
  Cargo.toml
Labels: breaking

#8 Serialization
  src/callsign.rs
  src/error.rs
  src/lib.rs
  src/lonlat.rs
  src/message.rs
  src/packet.rs
  src/position.rs
  src/timestamp.rs
Labels: enhancement, breaking

#43 Add APRS protocol reference
  docs/APRS101.PDF
Labels: documentation
